package githook

import (
	"fmt"
	"os"
	"path/filepath"
)

const preCommitScript = `#!/bin/sh
# SKIL Pre-Commit Security Guard
# Auto-generated by skil hook install. Do not edit manually.

echo "[skil] Running pre-commit security checks..."

if command -v skil >/dev/null 2>&1; then
  SKIL_BIN="skil"
else
  SKIL_BIN="go run ./cmd/skil"
fi

$SKIL_BIN fix --dry-run --workspace .
FIX_STATUS=$?

if [ $FIX_STATUS -ne 0 ]; then
  echo "[skil] PRE-COMMIT BLOCKED: Unsatisfied SKIL remediations or surface lock drift detected."
  echo "[skil] Run 'skil fix --workspace .' to remediate before committing."
  exit 1
fi

echo "[skil] Pre-commit security check passed."
exit 0
`

func InstallHook(workspaceRoot string, strict bool) error {
	cleanRoot := filepath.Clean(workspaceRoot)
	gitDir := filepath.Join(cleanRoot, ".git")

	info, err := os.Stat(gitDir)
	if os.IsNotExist(err) || !info.IsDir() {
		return fmt.Errorf("git repository not found at %s (.git directory missing)", cleanRoot)
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("create git hooks directory: %w", err)
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")
	if err := os.WriteFile(hookPath, []byte(preCommitScript), 0755); err != nil {
		return fmt.Errorf("write git pre-commit hook: %w", err)
	}

	return nil
}

func UninstallHook(workspaceRoot string) error {
	cleanRoot := filepath.Clean(workspaceRoot)
	hookPath := filepath.Join(cleanRoot, ".git", "hooks", "pre-commit")

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		return nil
	}

	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("remove git pre-commit hook: %w", err)
	}

	return nil
}
