package githook

import (
	"fmt"
	"os"
	"path/filepath"
)

const preCommitScript = `#!/bin/sh
# SKIL Pre-Commit Security Guard
# Auto-generated by skil hook install. Do not edit manually.

echo "[skil] Running pre-commit security checks..."

if command -v skil >/dev/null 2>&1; then
  SKIL_BIN="skil"
else
  SKIL_BIN="go run ./cmd/skil"
fi

if [ -f "SKILL.md" ] || [ -f "skil.yaml" ]; then
  $SKIL_BIN scan . --static-only >/dev/null 2>&1
  STATUS=$?
  if [ $STATUS -ne 0 ]; then
    echo "[skil] PRE-COMMIT BLOCKED: Security scan failed for skill in current directory."
    exit 1
  fi
fi

echo "[skil] Pre-commit security check passed."
exit 0
`

const prePushScript = `#!/bin/sh
# SKIL Pre-Push Security & Assurance Guard
# Auto-generated by skil hook install. Do not edit manually.

echo "[skil] Running pre-push security & validation checks..."

if command -v skil >/dev/null 2>&1; then
  SKIL_BIN="skil"
else
  SKIL_BIN="go run ./cmd/skil"
fi

if [ -f "SKILL.md" ] || [ -f "skil.yaml" ]; then
  $SKIL_BIN scan . --static-only >/dev/null 2>&1
  STATUS=$?
  if [ $STATUS -ne 0 ]; then
    echo "[skil] PRE-PUSH BLOCKED: Security scan failed for skill in current directory."
    exit 1
  fi
fi

if command -v go >/dev/null 2>&1; then
  go vet ./...
  VET_STATUS=$?
  if [ $VET_STATUS -ne 0 ]; then
    echo "[skil] PRE-PUSH BLOCKED: 'go vet' static analysis failed."
    exit 1
  fi
fi

echo "[skil] Pre-push security & validation check passed."
exit 0
`

func InstallHook(workspaceRoot string, strict bool) error {
	cleanRoot := filepath.Clean(workspaceRoot)
	gitDir := filepath.Join(cleanRoot, ".git")

	info, err := os.Stat(gitDir)
	if os.IsNotExist(err) || !info.IsDir() {
		return fmt.Errorf("git repository not found at %s (.git directory missing)", cleanRoot)
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("create git hooks directory: %w", err)
	}

	preCommitPath := filepath.Join(hooksDir, "pre-commit")
	if err := os.WriteFile(preCommitPath, []byte(preCommitScript), 0755); err != nil {
		return fmt.Errorf("write git pre-commit hook: %w", err)
	}

	prePushPath := filepath.Join(hooksDir, "pre-push")
	if err := os.WriteFile(prePushPath, []byte(prePushScript), 0755); err != nil {
		return fmt.Errorf("write git pre-push hook: %w", err)
	}

	return nil
}

func UninstallHook(workspaceRoot string) error {
	cleanRoot := filepath.Clean(workspaceRoot)
	hooksDir := filepath.Join(cleanRoot, ".git", "hooks")

	for _, name := range []string{"pre-commit", "pre-push"} {
		hookPath := filepath.Join(hooksDir, name)
		if _, err := os.Stat(hookPath); err == nil {
			if err := os.Remove(hookPath); err != nil {
				return fmt.Errorf("remove git %s hook: %w", name, err)
			}
		}
	}

	return nil
}
